name: Trigger biweekly report (test)
on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes for testing
  workflow_dispatch:        # allow manual run

jobs:
  call-endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger biweekly report
        run: |
            curl -sS -X POST "$APP_URL/api/reports/biweekly?force=1" \
            -H "x-cron-secret: $CRON_SECRET"
    env:
      APP_URL: ${{ secrets.APP_URL }}
      CRON_SECRET: ${{ secrets.CRON_SECRET }}
