name: Trigger biweekly report (test)
on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes for testing
  workflow_dispatch:        # allow manual run

jobs:
  call-endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: POST to /api/reports/biweekly
        run: |
          curl -sS -X POST "${{ secrets.NEXTAUTH_URL }}/api/reports/biweekly" \
            -H "x-cron-secret: ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json" \
            -d '{"dryRun": true}'
